spring.application.name=ads
server.port=8080

spring.datasource.url= jdbc:postgresql://localhost:5432/ads_db
spring.datasource.username= db_editor
spring.datasource.password= rooteditor
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto= none
spring.jpa.show-sql=true
spring.main.allow-bean-definition-overriding=true
spring.jpa.open-in-view=true

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.liquibase.url= jdbc:postgresql://localhost:5432/ads_db
spring.liquibase.user= db_editor
spring.liquibase.password= rooteditor

#??? ???????? ???????????? https://drive.google.com/drive/folders/1u5_7dWSBFABCbsnH5eAjtXRbYT7Znuft?usp=drive_link
#??? ???????? ?????? https://drive.google.com/drive/folders/1fDca-OClmKiG3Z9pzigItvZ-zPkPDzFo?usp=drive_link
